### ISSUE TITLE
Nickname G Detector doesn't work as intended

### ISSUE THREAD

**Issue by SuperchupuDev** [h-projects/gasbot#6]
### **We added a G Detector for nicknames back in June, and since then it's been broken**

If you chanqe your nickname to somethinq that triqqers the detector (for example `test g test`) it stays like that
then if u chanqe it back to anythinq that doesn't triqqer the detector (for example `the war`)
it chanqes your nickname like we planned (in this case to `test h test`), but only after chanqinq the detected nickname

![nickname_detector_broken](https://user-images.githubusercontent.com/53496941/94293644-801ee480-ff56-11ea-979b-9e4a907d2cb0.gif)

**We are planninq to fix this for ~~v2.1.0~~ v2.2.0**

**Comment by Indexerrowaty** [comment]
Yes

**Comment by Senko-Dev** [comment]
The bot was ᗷᕼᑌᗴᔕᒍYᗴᔕed. Fucking Charli ruined the bot.

**Comment by Indexerrowaty** [comment]
> The bot was ᗷᕼᑌᗴᔕᒍYᗴᔕed. Fucking Charli ruined the bot.

Don't forget that you became charli simp.

**Comment by Senko-Dev** [comment]
Oh god.

**Comment by Indexerrowaty** [comment]
Things to do:
- [x] Make changing nicknames work
- [ ] Make it 100% working as intended.

**Comment by DevSenko** [comment]
It needs to run on .emit events

**Comment by SuperchupuDev** [comment]
Finally after 4 months the guildMemberUpdate is working again for some reason, the issue could be fixed soon™!
![image](https://user-images.githubusercontent.com/53496941/108121407-ad516800-709a-11eb-814f-40dee954e46b.png)

**Comment by SuperchupuDev** [comment]
The Nickname Detector was polished and finished on a6ec061, closinq this issue
